[package]
name = "quick-deref-core"
version.workspace = true
edition.workspace = true

[dependencies]
darling = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
