[package]
name = "quick-default-macro"
edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
proc-macro2.workspace = true
quick-default-core.workspace = true