[package]
name = "quick-deref-core"
version = "0.1.0"
edition = "2024"

[dependencies]
darling = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
