[package]
name = "quick-def-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.91"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full"] }
